broker_url = "redis://localhost:6379/1"
result_backend = "redis://localhost:6379/1"
task_default_queue = "automation_articles_111"
task_serializer = "json"
accept_content = ["json"]
result_serializer = "json"
timezone = "Africa/Casablanca"
enable_utc = True
task_track_started = True
task_time_limit = 3600
task_soft_time_limit = 3300
worker_prefetch_multiplier = 1  # one task at a time — avoids memory spikes
task_acks_late = True           # re-queue on worker crash
worker_concurrency = 1          # process one pipeline at a time to respect API rate limits
